
package ifpb.pos.soap.reservapassagem;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ReservaPassagemResources", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReservaPassagemResources {


    /**
     * 
     * @param arg0
     * @return
     *     returns ifpb.pos.soap.reservapassagem.ReservaPassagem
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addReservaPassagem", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.reservapassagem.AddReservaPassagem")
    @ResponseWrapper(localName = "addReservaPassagemResponse", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.reservapassagem.AddReservaPassagemResponse")
    public ReservaPassagem addReservaPassagem(
        @WebParam(name = "arg0", targetNamespace = "")
        ReservaPassagem arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns ifpb.pos.soap.reservapassagem.ReservaPassagem
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReserva", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.reservapassagem.GetReserva")
    @ResponseWrapper(localName = "getReservaResponse", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.reservapassagem.GetReservaResponse")
    public ReservaPassagem getReserva(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns ifpb.pos.soap.reservapassagem.ReservaPassagem
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateReserva", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.reservapassagem.UpdateReserva")
    @ResponseWrapper(localName = "updateReservaResponse", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.reservapassagem.UpdateReservaResponse")
    public ReservaPassagem updateReserva(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        ReservaPassagem arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns ifpb.pos.soap.reservapassagem.ReservaPassagem
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteReserva", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.reservapassagem.DeleteReserva")
    @ResponseWrapper(localName = "deleteReservaResponse", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.reservapassagem.DeleteReservaResponse")
    public ReservaPassagem deleteReserva(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @return
     *     returns java.util.List<ifpb.pos.soap.reservapassagem.ReservaPassagem>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarReservasPassagem", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.reservapassagem.ListarReservasPassagem")
    @ResponseWrapper(localName = "listarReservasPassagemResponse", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.reservapassagem.ListarReservasPassagemResponse")
    public List<ReservaPassagem> listarReservasPassagem();

}
