
package ifpb.pos.soap.reservapassagem;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ReservaPassagemResourcesService", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", wsdlLocation = "http://localhost:8080/ativ2-soap-server/ReservaPassagemResourcesService?wsdl")
public class ReservaPassagemResourcesService
    extends Service
{

    private final static URL RESERVAPASSAGEMRESOURCESSERVICE_WSDL_LOCATION;
    private final static WebServiceException RESERVAPASSAGEMRESOURCESSERVICE_EXCEPTION;
    private final static QName RESERVAPASSAGEMRESOURCESSERVICE_QNAME = new QName("http://resources.soap.ativ2.pos.ifpb/", "ReservaPassagemResourcesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ativ2-soap-server/ReservaPassagemResourcesService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RESERVAPASSAGEMRESOURCESSERVICE_WSDL_LOCATION = url;
        RESERVAPASSAGEMRESOURCESSERVICE_EXCEPTION = e;
    }

    public ReservaPassagemResourcesService() {
        super(__getWsdlLocation(), RESERVAPASSAGEMRESOURCESSERVICE_QNAME);
    }

    public ReservaPassagemResourcesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ReservaPassagemResources
     */
    @WebEndpoint(name = "ReservaPassagemResourcesPort")
    public ReservaPassagemResources getReservaPassagemResourcesPort() {
        return super.getPort(new QName("http://resources.soap.ativ2.pos.ifpb/", "ReservaPassagemResourcesPort"), ReservaPassagemResources.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReservaPassagemResources
     */
    @WebEndpoint(name = "ReservaPassagemResourcesPort")
    public ReservaPassagemResources getReservaPassagemResourcesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://resources.soap.ativ2.pos.ifpb/", "ReservaPassagemResourcesPort"), ReservaPassagemResources.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RESERVAPASSAGEMRESOURCESSERVICE_EXCEPTION!= null) {
            throw RESERVAPASSAGEMRESOURCESSERVICE_EXCEPTION;
        }
        return RESERVAPASSAGEMRESOURCESSERVICE_WSDL_LOCATION;
    }

}
