
package ifpb.pos.soap.reservahotel;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ReservaHotelResourcesService", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", wsdlLocation = "http://localhost:8080/ativ2-soap-server/ReservaHotelResourcesService?wsdl")
public class ReservaHotelResourcesService
    extends Service
{

    private final static URL RESERVAHOTELRESOURCESSERVICE_WSDL_LOCATION;
    private final static WebServiceException RESERVAHOTELRESOURCESSERVICE_EXCEPTION;
    private final static QName RESERVAHOTELRESOURCESSERVICE_QNAME = new QName("http://resources.soap.ativ2.pos.ifpb/", "ReservaHotelResourcesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ativ2-soap-server/ReservaHotelResourcesService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RESERVAHOTELRESOURCESSERVICE_WSDL_LOCATION = url;
        RESERVAHOTELRESOURCESSERVICE_EXCEPTION = e;
    }

    public ReservaHotelResourcesService() {
        super(__getWsdlLocation(), RESERVAHOTELRESOURCESSERVICE_QNAME);
    }

    public ReservaHotelResourcesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ReservaHotelResources
     */
    @WebEndpoint(name = "ReservaHotelResourcesPort")
    public ReservaHotelResources getReservaHotelResourcesPort() {
        return super.getPort(new QName("http://resources.soap.ativ2.pos.ifpb/", "ReservaHotelResourcesPort"), ReservaHotelResources.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReservaHotelResources
     */
    @WebEndpoint(name = "ReservaHotelResourcesPort")
    public ReservaHotelResources getReservaHotelResourcesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://resources.soap.ativ2.pos.ifpb/", "ReservaHotelResourcesPort"), ReservaHotelResources.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RESERVAHOTELRESOURCESSERVICE_EXCEPTION!= null) {
            throw RESERVAHOTELRESOURCESSERVICE_EXCEPTION;
        }
        return RESERVAHOTELRESOURCESSERVICE_WSDL_LOCATION;
    }

}
