
package ifpb.pos.soap.reservahotel;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ReservaHotelResources", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReservaHotelResources {


    /**
     * 
     * @return
     *     returns java.util.List<ifpb.pos.soap.reservahotel.ReservaHotel>
     */
    @WebMethod
    @WebResult(name = "reservas", targetNamespace = "")
    @RequestWrapper(localName = "listarReservasHotel", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.reservahotel.ListarReservasHotel")
    @ResponseWrapper(localName = "listarReservasHotelResponse", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.reservahotel.ListarReservasHotelResponse")
    public List<ReservaHotel> listarReservasHotel();

    /**
     * 
     * @param arg0
     * @return
     *     returns ifpb.pos.soap.reservahotel.ReservaHotel
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addReserva", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.reservahotel.AddReserva")
    @ResponseWrapper(localName = "addReservaResponse", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.reservahotel.AddReservaResponse")
    public ReservaHotel addReserva(
        @WebParam(name = "arg0", targetNamespace = "")
        ReservaHotel arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns ifpb.pos.soap.reservahotel.ReservaPassagem
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReserva", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.reservahotel.GetReserva")
    @ResponseWrapper(localName = "getReservaResponse", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.reservahotel.GetReservaResponse")
    public ReservaPassagem getReserva(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns ifpb.pos.soap.reservahotel.ReservaPassagem
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateReserva", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.reservahotel.UpdateReserva")
    @ResponseWrapper(localName = "updateReservaResponse", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.reservahotel.UpdateReservaResponse")
    public ReservaPassagem updateReserva(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        ReservaPassagem arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns ifpb.pos.soap.reservahotel.ReservaPassagem
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteReserva", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.reservahotel.DeleteReserva")
    @ResponseWrapper(localName = "deleteReservaResponse", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.reservahotel.DeleteReservaResponse")
    public ReservaPassagem deleteReserva(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

}
