
package ifpb.pos.soap.hotel;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HotelResourcesService", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", wsdlLocation = "http://localhost:8080/ativ2-soap-server/HotelResourcesService?wsdl")
public class HotelResourcesService
    extends Service
{

    private final static URL HOTELRESOURCESSERVICE_WSDL_LOCATION;
    private final static WebServiceException HOTELRESOURCESSERVICE_EXCEPTION;
    private final static QName HOTELRESOURCESSERVICE_QNAME = new QName("http://resources.soap.ativ2.pos.ifpb/", "HotelResourcesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ativ2-soap-server/HotelResourcesService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HOTELRESOURCESSERVICE_WSDL_LOCATION = url;
        HOTELRESOURCESSERVICE_EXCEPTION = e;
    }

    public HotelResourcesService() {
        super(__getWsdlLocation(), HOTELRESOURCESSERVICE_QNAME);
    }

    public HotelResourcesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns HotelResources
     */
    @WebEndpoint(name = "HotelResourcesPort")
    public HotelResources getHotelResourcesPort() {
        return super.getPort(new QName("http://resources.soap.ativ2.pos.ifpb/", "HotelResourcesPort"), HotelResources.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HotelResources
     */
    @WebEndpoint(name = "HotelResourcesPort")
    public HotelResources getHotelResourcesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://resources.soap.ativ2.pos.ifpb/", "HotelResourcesPort"), HotelResources.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HOTELRESOURCESSERVICE_EXCEPTION!= null) {
            throw HOTELRESOURCESSERVICE_EXCEPTION;
        }
        return HOTELRESOURCESSERVICE_WSDL_LOCATION;
    }

}
