
package ifpb.pos.soap.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ClienteResourcesService", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", wsdlLocation = "http://localhost:8080/ativ2-soap-server/ClienteResourcesService?wsdl")
public class ClienteResourcesService
    extends Service
{

    private final static URL CLIENTERESOURCESSERVICE_WSDL_LOCATION;
    private final static WebServiceException CLIENTERESOURCESSERVICE_EXCEPTION;
    private final static QName CLIENTERESOURCESSERVICE_QNAME = new QName("http://resources.soap.ativ2.pos.ifpb/", "ClienteResourcesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ativ2-soap-server/ClienteResourcesService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLIENTERESOURCESSERVICE_WSDL_LOCATION = url;
        CLIENTERESOURCESSERVICE_EXCEPTION = e;
    }

    public ClienteResourcesService() {
        super(__getWsdlLocation(), CLIENTERESOURCESSERVICE_QNAME);
    }

    public ClienteResourcesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ClienteResources
     */
    @WebEndpoint(name = "ClienteResourcesPort")
    public ClienteResources getClienteResourcesPort() {
        return super.getPort(new QName("http://resources.soap.ativ2.pos.ifpb/", "ClienteResourcesPort"), ClienteResources.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClienteResources
     */
    @WebEndpoint(name = "ClienteResourcesPort")
    public ClienteResources getClienteResourcesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://resources.soap.ativ2.pos.ifpb/", "ClienteResourcesPort"), ClienteResources.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLIENTERESOURCESSERVICE_EXCEPTION!= null) {
            throw CLIENTERESOURCESSERVICE_EXCEPTION;
        }
        return CLIENTERESOURCESSERVICE_WSDL_LOCATION;
    }

}
