
package ifpb.pos.soap.cliente;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ClienteResources", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClienteResources {


    /**
     * 
     * @param arg0
     * @return
     *     returns ifpb.pos.soap.cliente.Cliente
     */
    @WebMethod
    @WebResult(name = "cliente", targetNamespace = "")
    @RequestWrapper(localName = "getClient", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.cliente.GetClient")
    @ResponseWrapper(localName = "getClientResponse", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.cliente.GetClientResponse")
    public Cliente getClient(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @return
     *     returns java.util.List<ifpb.pos.soap.cliente.Cliente>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarClientes", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.cliente.ListarClientes")
    @ResponseWrapper(localName = "listarClientesResponse", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.cliente.ListarClientesResponse")
    public List<Cliente> listarClientes();

    /**
     * 
     * @param arg0
     * @return
     *     returns ifpb.pos.soap.cliente.Cliente
     */
    @WebMethod
    @WebResult(name = "newCliente", targetNamespace = "")
    @RequestWrapper(localName = "addClient", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.cliente.AddClient")
    @ResponseWrapper(localName = "addClientResponse", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.cliente.AddClientResponse")
    public Cliente addClient(
        @WebParam(name = "arg0", targetNamespace = "")
        Cliente arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns ifpb.pos.soap.cliente.Cliente
     */
    @WebMethod
    @WebResult(name = "cliente.atualizado", targetNamespace = "")
    @RequestWrapper(localName = "updateClient", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.cliente.UpdateClient")
    @ResponseWrapper(localName = "updateClientResponse", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.cliente.UpdateClientResponse")
    public Cliente updateClient(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Cliente arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns ifpb.pos.soap.cliente.Cliente
     */
    @WebMethod
    @WebResult(name = "cliente.removido", targetNamespace = "")
    @RequestWrapper(localName = "deleteClient", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.cliente.DeleteClient")
    @ResponseWrapper(localName = "deleteClientResponse", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.cliente.DeleteClientResponse")
    public Cliente deleteClient(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

}
