
package ifpb.pos.soap.empresa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "EmpresaResourcesService", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", wsdlLocation = "http://localhost:8080/ativ2-soap-server/EmpresaResourcesService?wsdl")
public class EmpresaResourcesService
    extends Service
{

    private final static URL EMPRESARESOURCESSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPRESARESOURCESSERVICE_EXCEPTION;
    private final static QName EMPRESARESOURCESSERVICE_QNAME = new QName("http://resources.soap.ativ2.pos.ifpb/", "EmpresaResourcesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ativ2-soap-server/EmpresaResourcesService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPRESARESOURCESSERVICE_WSDL_LOCATION = url;
        EMPRESARESOURCESSERVICE_EXCEPTION = e;
    }

    public EmpresaResourcesService() {
        super(__getWsdlLocation(), EMPRESARESOURCESSERVICE_QNAME);
    }

    public EmpresaResourcesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns EmpresaResources
     */
    @WebEndpoint(name = "EmpresaResourcesPort")
    public EmpresaResources getEmpresaResourcesPort() {
        return super.getPort(new QName("http://resources.soap.ativ2.pos.ifpb/", "EmpresaResourcesPort"), EmpresaResources.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmpresaResources
     */
    @WebEndpoint(name = "EmpresaResourcesPort")
    public EmpresaResources getEmpresaResourcesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://resources.soap.ativ2.pos.ifpb/", "EmpresaResourcesPort"), EmpresaResources.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPRESARESOURCESSERVICE_EXCEPTION!= null) {
            throw EMPRESARESOURCESSERVICE_EXCEPTION;
        }
        return EMPRESARESOURCESSERVICE_WSDL_LOCATION;
    }

}
