
package ifpb.pos.soap.pacote;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PacoteResources", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PacoteResources {


    /**
     * 
     * @return
     *     returns java.util.List<ifpb.pos.soap.pacote.Pacote>
     */
    @WebMethod
    @WebResult(name = "pacotes", targetNamespace = "")
    @RequestWrapper(localName = "listarPacotes", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.pacote.ListarPacotes")
    @ResponseWrapper(localName = "listarPacotesResponse", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.pacote.ListarPacotesResponse")
    public List<Pacote> listarPacotes();

    /**
     * 
     * @param arg0
     * @return
     *     returns ifpb.pos.soap.pacote.Pacote
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "criaPacote", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.pacote.CriaPacote")
    @ResponseWrapper(localName = "criaPacoteResponse", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.pacote.CriaPacoteResponse")
    public Pacote criaPacote(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns ifpb.pos.soap.pacote.Pacote
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPacote", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.pacote.GetPacote")
    @ResponseWrapper(localName = "getPacoteResponse", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.pacote.GetPacoteResponse")
    public Pacote getPacote(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns ifpb.pos.soap.pacote.ReservaPassagem
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteReserva", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.pacote.DeleteReserva")
    @ResponseWrapper(localName = "deleteReservaResponse", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.pacote.DeleteReservaResponse")
    public ReservaPassagem deleteReserva(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns ifpb.pos.soap.pacote.Pacote
     */
    @WebMethod
    @WebResult(name = "novaReservaHotelPacote", targetNamespace = "")
    @RequestWrapper(localName = "addReservaHotelParaPacote", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.pacote.AddReservaHotelParaPacote")
    @ResponseWrapper(localName = "addReservaHotelParaPacoteResponse", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.pacote.AddReservaHotelParaPacoteResponse")
    public Pacote addReservaHotelParaPacote(
        @WebParam(name = "arg0", targetNamespace = "")
        Pacote arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Long arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns ifpb.pos.soap.pacote.Pacote
     */
    @WebMethod
    @WebResult(name = "novaReservaPassagemPacote", targetNamespace = "")
    @RequestWrapper(localName = "addReservaPassagemParaPacote", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.pacote.AddReservaPassagemParaPacote")
    @ResponseWrapper(localName = "addReservaPassagemParaPacoteResponse", targetNamespace = "http://resources.soap.ativ2.pos.ifpb/", className = "ifpb.pos.soap.pacote.AddReservaPassagemParaPacoteResponse")
    public Pacote addReservaPassagemParaPacote(
        @WebParam(name = "arg0", targetNamespace = "")
        Pacote arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Long arg1);

}
